apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: probes
  name: metrics-server-prober
spec:
  endpoints:
    - interval: 10s
      port: metrics
  namespaceSelector:
    matchNames:
      - probes
  selector:
    matchLabels:
      probe: metrics-server-prober
