apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: metrics-server-prober
  rules:
    - apiGroups:
        - "metrics.k8s.io"
      resources:
        - "pods"
        - "nodes"
      verbs:
        - get
        - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: metrics-server-prober
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: metrics-server-prober
  subjects:
    - kind: ServiceAccount
      name: metrics-server-prober
      namespace: probes
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: metrics-server-prober
    namespace: probes
