apiVersion: "clusterloader.io/v1alpha1"
kind: NetworkTestRequest
metadata:
  name: network-test-{{.index}}
  namespace: netperf
  labels:
   {{.clientPodName}}: clientPodName
   {{.serverPodName}}: serverPodName
spec:
  clientPodName: {{.clientPodName}} 
  serverPodName : {{.serverPodName}}
  serverPodIP: {{.serverPodIP}}
  protocol: {{.protocol}}
  duration: {{.duration}}
  clientStartTimestamp: {{.clientStartTimestamp}}
  numberOfClients: {{.numberOfClients}}
status:
  metrics: []
