apiVersion: v1
kind: Pod
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    k8s-app: node-exporter
spec:
  containers:
    - name: prometheus-node-exporter
      image: gcr.io/k8s-testimages/quay.io/prometheus/node-exporter:v1.0.1
      imagePullPolicy: "IfNotPresent"
      args:
        - --path.sysfs=/host/sys
        - --path.rootfs=/host/root
        - --no-collector.wifi
        - --no-collector.hwmon
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
        - --collector.netstat.fields=^.*$
        - --collector.qdisc
      ports:
        - name: metrics
          containerPort: 9100
          hostPort: 9100
      volumeMounts:
        - mountPath: /host/sys
          mountPropagation: HostToContainer
          name: sys
          readOnly: true
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
      resources:
        limits:
          cpu: 10m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 50Mi
  hostNetwork: true
  hostPID: true
  volumes:
    - hostPath:
        path: /sys
      name: sys
    - hostPath:
        path: /
      name: root
