apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}
  labels:
    group: test-job
spec:
  parallelism: {{.Replicas}}
  completions: {{.Replicas}}
  completionMode: {{.Mode}}
  template:
    metadata:
      labels:
        group: test-pod
    spec:
      containers:
      - name: {{.Name}}
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args:
          - "30s"
      restartPolicy: Never
