apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: resource-consumer-hpa
  namespace: default
spec:
  maxReplicas: 80
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-consumer
  targetCPUUtilizationPercentage: 50
