kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Name}}
subjects:
- kind: ServiceAccount
  name: {{.Name}}
  namespace: {{.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{.Name}}
  apiGroup: rbac.authorization.k8s.io
