apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: windows-exporter
  name: windows-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9182
    targetPort: http
  selector:
    k8s-app: windows-exporter
