apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    test: l4lb-load
  annotations:
    networking.gke.io/load-balancer-type: {{.LoadBalancerType}}
spec:
  externalTrafficPolicy: {{.ExternalTrafficPolicy}}
  type: LoadBalancer
  selector:
    name: {{.DeploymentBaseName}}-{{.Index}}
  ports:
  - port: 80
    targetPort: 80
